name: share_plus_package
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Share Plus
  share_plus: ^6.3.1
  # Image Picker => to get image from gallery. Supports Android, iOS and Web
  image_picker: ^0.8.6+1
  # File Selector => for windows, macos & Linux, since `package:image_picker` is not supported.
  file_selector: ^0.9.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_logo.png